import { test, expect } from "@playwright/test";
import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";

test("generates questions through a configured processor and reviews training and evaluation exports independently", async ({ page, request }) => {
  const configured = await request.post("/api/settings/providers/openai-compatible", { data: {
    enabled: true, baseUrl: "http://127.0.0.1:4312/v1", modelName: "browser-test", apiKey: "test-only-key",
    protocol: "openai-completions", contextWindow: 32768, maxTokens: 4096, reasoning: false, thinkingLevel: "off", supportsImages: true,
  } });
  expect(configured.ok()).toBeTruthy();
  const tag = "generated" + randomUUID().slice(0, 8);
  const created = await request.post("/api/memories", { data: { title: tag, content: "虚构记录：林舟把备用钥匙交给陈默，陈默随后保管钥匙。" } });
  expect(created.ok()).toBeTruthy(); const entry = (await created.json()).memory;
  await page.goto("/"); await page.getByRole("button", { name: "记忆", exact: true }).click();
  await page.getByRole("tab", { name: "记忆记录", exact: true }).click();
  const library = page.getByTestId("memory-library"); await library.getByLabel("搜索记忆").fill(tag);
  await library.getByRole("checkbox", { name: `选择记忆 ${tag}`, exact: true }).check();
  await library.getByRole("button", { name: "数据集", exact: true }).click();
  const list = page.getByRole("dialog", { name: "数据集", exact: true });
  await list.getByLabel("名称", { exact: true }).fill(tag);
  await list.getByLabel("样本生成", { exact: true }).click(); await page.getByRole("option", { name: "browser-test", exact: true }).click();
  await list.getByRole("button", { name: "从所选 1 条构建" }).click();
  const row = list.getByTestId("dataset-row").filter({ hasText: tag }); await expect(row).toContainText("已构建");
  await expect(row).toContainText("1 次调用"); await row.getByRole("button", { name: "查看样本" }).click();
  const samples = page.getByRole("dialog", { name: tag, exact: true });
  await expect(samples).toContainText("3 条样本");
  await expect(samples.locator('[data-slot="accordion-item"]').getByText("待核对", { exact: true })).toHaveCount(3);
  const reviewed = samples.getByRole("checkbox", { name: /^选择样本 / });
  const exported = async (name: string) => {
    const waiting = page.waitForEvent("download"); await samples.getByRole("link", { name, exact: true }).click();
    return readFile((await (await waiting).path())!, "utf8");
  };
  expect(await exported("训练样本")).toBe(""); expect(await exported("评测题")).toBe("");
  for (let i = 0; i < 3; i++) await reviewed.nth(i).check();
  await samples.getByLabel("核对依据", { exact: true }).fill("测试原文明确记载钥匙、交接人和接收人，逐题核对问法。");
  await samples.getByRole("button", { name: "确认所选样本", exact: true }).click();
  await expect(samples.locator('[data-slot="accordion-item"]').getByText("可导出", { exact: true })).toHaveCount(3);
  await expect(samples.getByRole("link", { name: "评测题", exact: true })).toBeVisible();
  const training = (await exported("训练样本")).trim().split("\n").map((line) => JSON.parse(line));
  const evaluation = JSON.parse((await exported("评测题")).trim());
  expect(training).toHaveLength(2); expect(evaluation.expectedAnswer).toBe("陈默"); expect(evaluation.messages).toBeUndefined();
  expect(training.every((sample) => sample.messages[0].content !== evaluation.question)).toBeTruthy();
  expect(evaluation.lineage.memoryRefs).toEqual([{ id: entry.id, version: entry.version }]);
  expect(evaluation.evaluationOf).toEqual({ id: training.find((sample) => sample.messages[1].content === "陈默").sampleId, version: 2 });
  const id = evaluation.lineage.datasetId;
  const datasetResponse = await request.get(`/api/memory-datasets/${id}/samples`);
  const datasetSamples = (await datasetResponse.json()).samples;
  const paired = datasetSamples.find((sample: { id: string }) => sample.id === evaluation.evaluationOf.id);
  await samples.getByRole("button", { name: new RegExp(evaluation.question) }).click();
  await expect(samples.getByText("关联训练题 · v2", { exact: true })).toBeVisible();
  await samples.getByRole("button", { name: new RegExp(paired.question) }).first().click();
  const trainingItem = samples.locator('[data-slot="accordion-item"]').filter({ has: page.getByRole("button", { name: new RegExp(paired.question) }) });
  await trainingItem.getByRole("button", { name: "修订样本", exact: true }).click();
  await trainingItem.getByLabel("问题", { exact: true }).fill("林舟把备用钥匙交给哪位保管人？");
  await trainingItem.getByLabel("修订依据", { exact: true }).fill("原文明确接收与保管人为陈默，训练题改写后重新核对关联评测。");
  await trainingItem.getByRole("button", { name: "保存修订", exact: true }).click();
  await expect(samples.locator('[data-slot="accordion-item"]').getByText("待核对", { exact: true })).toHaveCount(1);
  expect((await exported("评测题")).trim()).toBe("");
  await page.setViewportSize({ width: 390, height: 844 });
  const evaluationItem = samples.locator('[data-slot="accordion-item"]').filter({ has: page.getByRole("button", { name: new RegExp(evaluation.question) }) });
  await expect(evaluationItem.getByText("关联训练题 · v3", { exact: true })).toBeVisible();
  await evaluationItem.getByRole("button", { name: "修订样本", exact: true }).click();
  await evaluationItem.getByLabel("关联训练题", { exact: true }).click();
  await page.getByRole("option", { name: "林舟把备用钥匙交给哪位保管人？", exact: true }).click();
  await evaluationItem.getByLabel("问题", { exact: true }).fill("林舟交出的备用钥匙由哪位接收并保管？");
  await evaluationItem.getByLabel("修订依据", { exact: true }).fill("两题均询问同次备用钥匙交接的接收与保管人，陈默来自同一冻结原文。");
  await page.screenshot({ path: "test-results/evaluation-pairing-mobile-edit.png", fullPage: true, animations: "disabled" });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await evaluationItem.getByRole("button", { name: "保存修订", exact: true }).click();
  await expect(samples.locator('[data-slot="accordion-item"]').getByText("可导出", { exact: true })).toHaveCount(3);
  const repairedEvaluation = JSON.parse((await exported("评测题")).trim());
  expect(repairedEvaluation.evaluationOf).toEqual({ id: paired.id, version: 3 });
  expect(repairedEvaluation.version).toBe(4);
  await page.screenshot({ path: "test-results/generated-dataset.png", fullPage: true, animations: "disabled" });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.reload(); await page.getByRole("button", { name: "记忆", exact: true }).click();
  await page.getByRole("tab", { name: "记忆记录", exact: true }).click();
  await page.getByTestId("memory-library").getByRole("button", { name: "数据集", exact: true }).click();
  const restored = page.getByRole("dialog", { name: "数据集", exact: true }).getByTestId("dataset-row").filter({ hasText: tag });
  await expect(restored).toContainText("已构建"); await expect(restored).toContainText("1 次调用");
  const restoredResponse = await request.get(`/api/memory-datasets/${id}/samples`);
  expect((await restoredResponse.json()).samples.find((sample: { id: string }) => sample.id === evaluation.sampleId).evaluationOf).toEqual({ id: paired.id, version: 3 });
  await restored.getByRole("button", { name: "查看样本", exact: true }).click();
  const auditControls = samples.getByTestId("dataset-audit-controls");
  await auditControls.getByRole("radio", { name: "全部问答", exact: true }).click();
  const auditSubmitted = page.waitForResponse((response) => response.url().endsWith(`/memory-datasets/${id}/audits`) && response.request().method() === "POST");
  await auditControls.getByRole("button", { name: "批量核验", exact: true }).click();
  const auditResponse = await auditSubmitted; expect(auditResponse.status()).toBe(202); const auditId = (await auditResponse.json()).audit.id;
  await expect(samples.getByRole("button", { name: "训练样本", exact: true })).toBeDisabled();
  await expect(samples.getByTestId("dataset-audit-summary")).toHaveAttribute("data-audit-status", "completed");
  await expect(auditControls).toContainText("认可 3");
  await auditControls.getByRole("button", { name: "查看核验记录", exact: true }).click();
  await expect(auditControls.getByTestId("dataset-audit-decisions").locator("tbody tr")).toHaveCount(3);
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await auditControls.evaluate((node) => node.getBoundingClientRect().right <= innerWidth)).toBeTruthy();
  expect(await auditControls.getByTestId("dataset-audit-decisions").evaluate((node) => node.scrollWidth <= node.clientWidth)).toBeTruthy();
  await page.screenshot({ path: "test-results/dataset-audit-mobile.png", fullPage: true, animations: "disabled" });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  const audited = (await (await request.get(`/api/memory-datasets/${id}/samples`)).json()).samples;
  expect(audited.every((sample: { authority: string; review: { actor: string; jobId: string } }) => sample.authority === "processor-reviewed" && sample.review.actor === "processor" && sample.review.jobId === auditId)).toBeTruthy();
  expect(audited.every((sample: { question: string; answer: string; answerCheck: { question: string; answerQuote: string; evidenceQuotes: string[] } }) =>
    sample.answerCheck.question === sample.question && sample.answerCheck.answerQuote === sample.answer && sample.answerCheck.evidenceQuotes.length > 0)).toBeTruthy();
  await samples.locator('[data-slot="accordion-trigger"]').first().click();
  await expect(samples.getByTestId("sample-answer-check").first()).toContainText("来源作答");
  await expect(samples.getByTestId("sample-answer-check").first()).toContainText(entry.content);
  expect(await samples.getByTestId("sample-answer-check").first().evaluate((node) => node.getBoundingClientRect().right <= innerWidth)).toBeTruthy();
  await page.screenshot({ path: "test-results/dataset-source-answer-mobile.png", fullPage: true, animations: "disabled" });
  await samples.getByRole("radio", { name: "待核对", exact: true }).click();
  await expect(samples.getByText("暂无待核对样本", { exact: true })).toBeVisible();
  await expect(samples.getByText("匹配 0 条", { exact: true })).toBeVisible();
  await samples.getByRole("radio", { name: "可导出", exact: true }).click();
  await expect(samples.locator('[data-slot="accordion-item"]')).toHaveCount(3);
  const currentTraining = audited.find((sample: { id: string }) => sample.id === paired.id);
  await auditControls.getByRole("button", { name: currentTraining.question, exact: true }).click();
  await expect(samples.locator('[data-slot="accordion-item"]')).toHaveCount(1);
  await expect(samples.getByText("匹配 1 条", { exact: true })).toBeVisible();
  const currentItem = samples.locator('[data-slot="accordion-item"]');
  await currentItem.getByRole("button", { name: new RegExp(currentTraining.question) }).click();
  await currentItem.getByRole("button", { name: "修订样本", exact: true }).click();
  await currentItem.getByLabel("修订依据", { exact: true }).fill("此隔离材料的交接时点待补充，暂不用于训练；保留当前人物与问答。");
  await currentItem.getByRole("button", { name: "保留待核对", exact: true }).click();
  await expect(currentItem.getByText("待核对", { exact: true })).toBeVisible();
  await samples.getByRole("radio", { name: "待核对", exact: true }).click();
  await expect(samples.getByText("匹配 2 条", { exact: true })).toBeVisible();
  await expect(samples.locator('[data-slot="accordion-item"]')).toHaveCount(2);
  expect((await exported("待审样本")).trim().split("\n")).toHaveLength(2);
  expect(await exported("评测题")).toBe("");
  expect((await exported("训练样本")).trim().split("\n")).toHaveLength(1);
  await samples.getByRole("radio", { name: "可导出", exact: true }).click();
  await expect(samples.locator('[data-slot="accordion-item"]')).toHaveCount(1);
  await page.screenshot({ path: "test-results/dataset-review-queue-mobile.png", fullPage: true, animations: "disabled" });
  await samples.getByRole("button", { name: "关闭", exact: true }).click();
  await page.setViewportSize({ width: 1440, height: 1000 });
  expect((await request.patch(`/api/memories/${entry.id}`, { data: { version: entry.version, content: "虚构纠正：陈默把备用钥匙交给林舟。" } })).ok()).toBeTruthy();
  await expect(restored).toContainText("依赖已变更");
  expect((await request.get(`/api/memory-datasets/${id}/files/evaluation`)).status()).toBe(409);
});

test("rebuilds corrected selected records, reuses unchanged samples and retains the stale previous version", async ({ page, request }) => {
  const tag = "dataset" + randomUUID().slice(0, 8);
  const entries = [];
  for (let i = 0; i < 2; i++) {
    const response = await request.post("/api/memories", { data: { title: tag + " " + i, content: `虚构数据集材料 ${tag} 第 ${i} 条。`, occurredAt: "2026-05-10" } });
    expect(response.ok()).toBeTruthy(); entries.push((await response.json()).memory);
  }
  await page.goto("/"); await page.getByRole("button", { name: "记忆", exact: true }).click();
  await page.getByRole("tab", { name: "记忆记录", exact: true }).click();
  const library = page.getByTestId("memory-library"); await library.getByLabel("搜索记忆").fill(tag);
  const boxes = library.getByRole("checkbox", { name: /^选择记忆 / }); await expect(boxes).toHaveCount(2);
  await boxes.nth(0).check(); await boxes.nth(1).check();
  await library.getByRole("button", { name: "数据集", exact: true }).click();
  const list = page.getByRole("dialog", { name: "数据集", exact: true }); await list.getByLabel("名称", { exact: true }).fill(tag);
  await list.getByLabel("样本生成", { exact: true }).click();
  await page.getByRole("option", { name: "固定模板", exact: true }).click();
  await list.getByRole("button", { name: "从所选 2 条构建" }).click();
  const row = list.getByTestId("dataset-row").filter({ hasText: tag }); await expect(row).toContainText("已构建");
  await row.getByRole("button", { name: "查看样本" }).click();
  let samples = page.getByRole("dialog", { name: tag, exact: true }); await expect(samples).toContainText("4 条样本");
  const waiting = page.waitForEvent("download"); await samples.getByRole("link", { name: "训练样本", exact: true }).click();
  const download = await waiting; const lines = (await readFile((await download.path())!, "utf8")).trim().split("\n").map((line) => JSON.parse(line));
  expect(lines).toHaveLength(4);
  expect(new Set(lines.map((line) => line.lineage.memoryRefs[0].id))).toEqual(new Set(entries.map((entry) => entry.id)));
  const id = lines[0].lineage.datasetId;
  await page.reload(); await page.getByRole("button", { name: "记忆", exact: true }).click();
  await page.getByRole("tab", { name: "记忆记录", exact: true }).click();
  await page.getByTestId("memory-library").getByRole("button", { name: "数据集", exact: true }).click();
  const restored = page.getByRole("dialog", { name: "数据集", exact: true }).getByTestId("dataset-row").filter({ hasText: tag });
  await expect(restored).toContainText("已构建");
  expect((await request.patch(`/api/memories/${entries[0].id}`, { data: { version: entries[0].version, content: "虚构记录已纠正。" } })).ok()).toBeTruthy();
  await expect(restored).toContainText("依赖已变更");
  await restored.getByRole("button", { name: "查看样本" }).click(); samples = page.getByRole("dialog", { name: tag, exact: true });
  await expect(samples.getByRole("button", { name: "训练样本", exact: true })).toBeDisabled();
  expect((await request.get(`/api/memory-datasets/${id}/files/training`)).status()).toBe(409);
  await page.screenshot({ path: "test-results/dataset-lineage.png", fullPage: true, animations: "disabled" });
  await page.setViewportSize({ width: 390, height: 844 });
  const rebuilding = page.waitForResponse((response) => response.url().endsWith(`/memory-datasets/${id}/rebuild`) && response.request().method() === "POST");
  await samples.getByRole("button", { name: "重新构建", exact: true }).click();
  const submitted = await rebuilding; expect(submitted.status()).toBe(202);
  const rebuiltId = (await submitted.json()).dataset.id;
  samples = page.getByRole("dialog", { name: tag, exact: true });
  await expect(samples.getByRole("link", { name: "训练样本", exact: true })).toBeVisible();
  await expect(samples).toContainText("更新 1 条记忆"); await expect(samples).toContainText("沿用 2 条样本");
  const updatedDownload = page.waitForEvent("download"); await samples.getByRole("link", { name: "训练样本", exact: true }).click();
  const updatedLines = (await readFile((await (await updatedDownload).path())!, "utf8")).trim().split("\n").map((line) => JSON.parse(line));
  expect(updatedLines).toHaveLength(4);
  expect(updatedLines.filter((line) => line.lineage.memoryRefs[0].id === entries[0].id).every((line) => line.messages[1].content === "虚构记录已纠正。" && line.lineage.memoryRefs[0].version === entries[0].version + 1)).toBeTruthy();
  expect(updatedLines.filter((line) => line.lineage.memoryRefs[0].id === entries[1].id).every((line) => line.reusedFrom.datasetId === id)).toBeTruthy();
  await page.screenshot({ path: "test-results/dataset-rebuild-mobile.png", fullPage: true, animations: "disabled" });
  await samples.getByRole("button", { name: "上一版本", exact: true }).click();
  await expect(samples).toContainText("依赖已变更"); await expect(samples.getByRole("button", { name: "训练样本", exact: true })).toBeDisabled();
  await page.reload(); await page.getByTestId("memory-library").getByRole("button", { name: "数据集", exact: true }).click();
  const datasetPage = page.getByRole("dialog", { name: "数据集", exact: true });
  await expect(datasetPage.getByTestId("dataset-row").filter({ hasText: tag })).toHaveCount(2);
  await expect(datasetPage.getByTestId("dataset-row").filter({ hasText: "重建版本" }).filter({ hasText: tag })).toContainText("沿用 2 条样本");
  expect((await request.get(`/api/memory-datasets/${rebuiltId}/files/training`)).ok()).toBeTruthy();
  expect((await request.get(`/api/memory-datasets/${id}/files/training`)).status()).toBe(409);
});

test("merges and splits confirmed event records through the review UI", async ({ page, request }) => {
  const tag = "event" + randomUUID().slice(0, 8);
  for (let i = 0; i < 2; i++) {
    const created = await request.post("/api/memories", { data: { title: tag + " " + i, content: "虚构事件记录 " + i, space: "demo", occurredAt: "2026-05-11" } });
    const entry = (await created.json()).memory;
    const patched = await request.patch(`/api/memories/${entry.id}`, { data: { version: entry.version, category: "event" } });
    expect(patched.ok()).toBeTruthy();
  }
  await page.goto("/?space=demo"); await page.getByRole("button", { name: "记忆", exact: true }).click();
  await page.getByRole("tab", { name: "记忆记录", exact: true }).click();
  await page.getByRole("tab", { name: "时间线", exact: true }).click();
  await page.getByRole("button", { name: "事件归组", exact: true }).click();
  let list = page.getByRole("dialog", { name: "事件归组", exact: true });
  await list.getByLabel("搜索事件").fill(tag);
  await expect(list.getByTestId("event-group")).toHaveCount(2);
  await list.getByRole("checkbox", { name: `选择事件 ${tag} 0`, exact: true }).check();
  await list.getByRole("checkbox", { name: `选择事件 ${tag} 1`, exact: true }).check();
  await list.getByLabel("合并后的事件名称").fill(tag + " 合并");
  await list.getByLabel("合并依据").fill("公开测试中明确关联同一事件");
  await list.getByRole("button", { name: "合并所选事件" }).click();
  await expect(list.getByTestId("event-group")).toHaveCount(1);
  await list.getByTestId("event-group").filter({ hasText: tag + " 合并" }).getByRole("button", { name: "查看记录" }).click();
  const members = page.getByRole("dialog", { name: tag + " 合并", exact: true });
  await members.getByRole("checkbox", { name: `分离记录 ${tag} 0`, exact: true }).check();
  await members.getByLabel("新事件名称").fill(tag + " 分离"); await members.getByLabel("分离依据").fill("纠正事件归属");
  await members.getByRole("button", { name: "分为新事件" }).click();
  await expect(members).toHaveCount(0);
  const split = await request.get("/api/memory-events?space=demo&query=" + tag);
  expect((await split.json()).total).toBe(2);
});
